#ifndef VFCRYPTOBRIDGE_GLOBAL_H
#define VFCRYPTOBRIDGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VFCRYPTOBRIDGE_LIBRARY)
#  define VFCRYPTOBRIDGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VFCRYPTOBRIDGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VFCRYPTOBRIDGE_GLOBAL_H
